import {chromium} from 'playwright';
const shot='C:/Users/pvenegas/AppData/Local/Temp/claude/c--Users-pvenegas-Documents-GitHub-lacalita-web/bc703168-3b4d-4260-85d0-34f9190e462d/scratchpad';
const b=await chromium.launch({channel:'chrome'});
const p=await b.newPage({viewport:{width:1280,height:900},deviceScaleFactor:2});
await p.goto('http://localhost:3002/es',{waitUntil:'networkidle'});
await p.getByRole('button',{name:/Aceptar/}).click().catch(()=>{});
await p.waitForTimeout(1500);
const sec=p.locator('#info');
await sec.scrollIntoViewIfNeeded(); await p.waitForTimeout(3500);
const bb=await sec.boundingBox();
await p.screenshot({path:`${shot}/pin.png`, clip:{x:640,y:bb.y+300,width:640,height:560}});
await b.close();
